d /var/lib/piavpn 0775 root piavpn -
d /var/run/piavpn 0775 root piavpn -
d /var/opt/piavpn 0755 root root -
L /var/opt/piavpn/bin - - - - /usr/lib/pia-engine/opt/piavpn/bin
L /var/opt/piavpn/lib - - - - /usr/lib/pia-engine/opt/piavpn/lib
L /var/opt/piavpn/var - - - - /var/lib/piavpn
